sinais/urls.py
from django.conf.urls import url
from sinais.views import index, exibir, RegistrarSinalView

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^sinais/(?P<sinal_id>\d+)$', 'sinais.views.exibir', name='exibir'),
    url(r'^registrar/$', RegistrarSinalView.as_view(), name='registrar'),

]

tradutor/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tradutor.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('sinais.urls'))
)

sinais/models.py
from django.db import models


# Create your models here.

class Sinal(models.Model):
    configuracao_da_mao = models.CharField(max_length=5, null=False)
    ponto_de_articulacao = models.CharField(max_length=5, null=False)
    movimento = models.CharField(max_length=5, null=False)
    orientacao_das_maos = models.CharField(max_length=5, null=False)
    expressao_facil_corporal = models.CharField(max_length=5, null=False)
    nome = models.CharField(max_length=255, null=False)

    def particionar(self, bitmask):
        i, l = 0, []
        while bitmask[i:i + 4]:
            l.append(bitmask[i:i + 4])
            i += 4
        # self.configuracao_da_mao = l[0]
        # self.ponto_de_articulacao = l[1]
        # self.movimento = l[2]
        # self.orientacao_das_maos = l[3]
        # self.expressao_facil_corporal = l[4]
        return l


# def get_bitmask_traduzido(request):
#         # return Sinal.objects.get(nome=)
#
#
# class Tradutor(models.Model):
#
#     # bitmask = models.ForeignKey(Perfil)


# configuracao_da_mao, ponto_de_articulacao, movimento, orientacao_das_maos, expressao_facil_corporal = bitmask.split()

sinais/forms.py
from django import forms
from django.db import models

# from django.contrib.auth.models import Sinal
from sinais.models import Sinal


class RegistrarSinalForm(forms.Form):
    configuracao_da_mao = forms.CharField(required=True)
    ponto_de_articulacao = forms.CharField(required=True)
    movimento = forms.CharField(required=True)
    orientacao_das_maos = forms.CharField(required=True)
    expressao_facil_corporal = forms.CharField(required=True)
    nome = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarSinalForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        sinal_exists = Sinal.objects.filter(nome=self.data['nome']).exists()

        if sinal_exists:
            self.adiciona_erro('Sinal ja existente')
            valid = False

        return valid


def adiciona_erro(self, message):
    errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
    errors.append(message)

sinais/views.py
from django.shortcuts import render
from sinais.models import Sinal
from django.views.generic.base import View
from sinais.forms import RegistrarSinalForm
from django.shortcuts import redirect


def index(request):
    return render(request, 'index.html', {'sinais': Sinal.objects.all()})


def exibir(request, sinal_id):
    sinal = Sinal.objects.get(id=sinal_id)
    return render(request, 'sinal.html', {"sinal": sinal})


class RegistrarSinalView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarSinalForm(request.POST)

        if form.is_valid():
            dados_form = form.data

            sinal = Sinal(configuracao_da_mao=dados_form['configuracao_da_mao'],
                          ponto_de_articulacao=dados_form['ponto_de_articulacao'],
                          movimento=dados_form['movimento'],
                          orientacao_das_maos=dados_form['orientacao_das_maos'],
                          expressao_facil_corporal=dados_form['expressao_facil_corporal'],
                          nome=dados_form['nome'])

            sinal.save()

            return redirect('index')


            # configuracao_da_mao = '1111', ponto_de_articulacao = '1111', movimento = '1111', orientacao_das_maos = '1111', expressao_facil_corporal = '1111', nome = 'odio'

        return render(request, self.template_name, {'form': form})

sinais/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "styles/main.css" %}" rel="stylesheet">
      <link href="{% static "styles/sinal.css" %}" rel="stylesheet">

    <title>Tradutor de libras</title>
  </head>
  <body>
      <div class="row content">
         {% block body %}
         {% endblock %}
      </div>
    </div>
  </body>
</html>

sinais/templates/base_registro.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">

        <title>Tradutor de Libras</title>

        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/signin.css" %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            {% block body %}

            {% endblock %}
        </div>
    </body>
</html>

sinais/templates/index.html
{% extends "base.html" %}

{% block body %}
        <div class="header">
        <center><h1 class="text-muted">Tradutor de Libras</h1></center>
    </div>

 <br><br><br><br><br><br><br><br>

    <center>
        <form>
        <input type="text" name="bitMask" value="" placeholder="BITMASK">
        <br>
        <br>
        <input type="submit" value="Traduzir">
        </form>
    </center>

        <br><br><br><br><br><br><br><br>
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Todos os Sinais Disponíveis</strong>
        </div>
          {% if sinais %}
            <ul>
                {% for sinal in sinais %}
                    <li>
                        <a href="{% url 'exibir' sinal.id %}">{{ sinal.nome|upper }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Nenhum Perfil encontrado</p>
        {% endif %}
    </div>
</div>
{% endblock %}

sinais/templates/registrar.html
{% extends "base_registro.html" %}

{% block body %}

  <form class="form-signin" action="{% url 'registrar' %}" method="post">

        {% csrf_token %}


    <h2 class="form-signin-heading">Criar um sinal</h2>

    <input type="text" id="id_co" name="configuracao_da_mao" class="form-control" placeholder="Configuração de Mão" required autofocus>

    <input type="text" id="id_pa" name="ponto_de_articulacao" class="form-control" placeholder="Ponto de articulação" required >

    <input type="text" id="id_m" name="movimento" class="form-control" placeholder="Movimento" required>

    <hr />

    <input type="text" id="id_o" name="orientacao_das_maos" class="form-control" placeholder="Orientação das mãos" required>

    <input type="text" id="id_efc" name="expressao_facil_corporal" class="form-control" placeholder="Expressão facil/corporal" required>

    <hr />

          <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome" required>
<hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

  <hr/>
       {% if form.errors %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{form.non_field_errors}}
      </div>
    {% endif %}

  </form>

{% endblock %}

sinais/templates/sinal.html
{% extends "base.html" %}

{% block body %}
        <div class="header">
        <center><h1 class="text-muted">Detalhe do Sinal</h1></center>
    </div>

<div class="row">
    <div class="col-lg-12">
        <h2 style="margin-top:0">Nome do Sinal: {{sinal.nome }}</h2>

        <dl>
            <dt>Parâmetros Primários</dt>
                <dd> Configuração da mão (CM): {{sinal.configuracao_da_mao}}</dd>
                <dd> Ponto de articulação (PA): {{sinal.ponto_de_articulacao}}</dd>
                <dd> Movimento (M): {{sinal.movimento}}</dd><br>
            <dt> Parâmetros Secundários</dt>
                <dd> Orientação das mãos (O): {{ sinal.orientacao_das_maos }}</dd>
                <dd> Expressão facil/corporal (EFC): {{sinal.expressao_facil_corporal}}</dd>
        </dl>
{#             configuracao da mao: {{sinal.configuracao_da_mao}}, ponto de articulacao: {{sinal.ponto_de_articulacao}},#}
{#   movimento: {{sinal.movimento}}, orientacao das maos: {{ sinal.orientacao_das_maos }},#}
{#   expressao facil corporal: {{sinal.expressao_facil_corporal}}#}
    </div>
</div>
{% endblock %}